version: '3'
services:
  web:
    image: nginx
    hostname: starter_web
    container_name: starter_web
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8114:80"
    restart: always
    depends_on:
      - php
    networks:
      - rts_starter

  php:
    build:
      context: .docker
      dockerfile: Dockerfile
    image: symfony:test-local
    restart: always
    hostname: starter_php
    container_name: starter_php
    volumes:
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/conf/php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
    networks:
      - rts_starter

  db:
    image: postgres:14
    restart: always
    hostname: starter_db
    container_name: starter_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "8115:5432"
    volumes:
      - ./.docker/volumes/db:/var/lib/postgresql/data:rw
      - ./.docker/dump/start.dump:/tmp/start.dump
    networks:
      - rts_starter

networks:
  rts_starter:
    driver: bridge
